Associate weight with p [For push-sum algorithm]
Bluefog-Lib/bluefog pull request #40
Opened 2020-08-19 07:05 UTC by Bluefog-Lib

2020-09-12 08:19 UTC, hanbinhu requested changes

2020-09-13 02:36 UTC, Bluefog-Lib commented on bluefog/torch/mpi_ops.py
> +def win_associated_p(name: str) -> float:
Done

2020-09-13 02:37 UTC, Bluefog-Lib commented on bluefog/torch/mpi_ops.py
> +def turn_on_win_ops_with_associated_p():
Done

2020-09-13 02:37 UTC, Bluefog-Lib commented on bluefog/torch/mpi_ops.py
> +def turn_off_win_ops_with_associated_p():
Done

2020-09-13 02:37 UTC, Bluefog-Lib commented on test/torch_win_ops_test.py
> +            dtypes += [torch.cuda.FloatTensor, torch.cuda.DoubleTensor]
So far. Yes. I don't see the problem yet.

2020-09-13 02:37 UTC, Bluefog-Lib commented on test/torch_win_ops_test.py
> +            assert abs(associated_p - tensor.data[0])< 0.1
You are right. Should use epsilon

2020-09-13 03:11 UTC, merged