Add Half tensor to MPI operations
Bluefog-Lib/bluefog pull request #43
Opened 2020-08-30 08:29 UTC by hanbinhu

2020-09-09 07:25 UTC, Bluefog-Lib requested changes

2020-09-09 07:25 UTC, Bluefog-Lib commented on bluefog/common/half.h
> +#ifndef BLUEFOG_HALF_H
我一般放全路径 BLUEFOG_COMMON_HALF_H. 不过都行

2020-09-09 07:25 UTC, Bluefog-Lib commented on bluefog/common/mpi_controller.cc
> +      mpi_ctx_.GetMPISumOp(entry.tensor->dtype()),
NCCL 这边是不是不用改， 直接支持？

2020-09-09 07:25 UTC, Bluefog-Lib commented on bluefog/torch/mpi_ops.py
> +        assert isinstance(tensor, (torch.HalfTensor, torch.FloatTensor, torch.DoubleTensor,
window 这些全都暂时不去支持是吧

2020-09-09 07:25 UTC, Bluefog-Lib commented on bluefog/torch/mpi_ops.cc
> +
为什么不把 is_cpu_half_tensor 放到两个函数里面去。
传统上可以叫他们 MaybeCopyToTensorBuffer， MaybeCopyBufferBack.
还有C++ 函数用Pascal Case.

2020-09-12 07:23 UTC, hanbinhu commented on bluefog/common/half.h
> +#ifndef BLUEFOG_HALF_H
Done

2020-09-12 07:23 UTC, hanbinhu commented on bluefog/common/mpi_controller.cc
> +      mpi_ctx_.GetMPISumOp(entry.tensor->dtype()),
估计是的，但我不是那么确定

2020-09-12 07:24 UTC, hanbinhu commented on bluefog/torch/mpi_ops.py
> +        assert isinstance(tensor, (torch.HalfTensor, torch.FloatTensor, torch.DoubleTensor,
暂时不考虑window这一边，先把cuda上的type搞定再说。

2020-09-12 07:34 UTC, hanbinhu commented on bluefog/torch/mpi_ops.cc
> +
Done.

2020-09-12 19:28 UTC, merged