Nccl win
Bluefog-Lib/bluefog pull request #46
Opened 2020-09-17 05:38 UTC by Bluefog-Lib

2020-09-18 07:55 UTC, hanbinhu requested changes

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/nccl_win.cc
> +  id_to_name_.erase(id_to_name_.find(id));
Check this as well?

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/nccl_win.cc
> +  return id_to_name_.at(id);
What if not found?

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/nccl_win.cc
> +  return name_to_id_.at(name);
Same here

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/torch/mpi_win_ops.cc
> +        tensor.to(::torch::Device(::torch::kCPU), /*non_blocking=*/false);
Is it safe to do so?

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/operations.cc
> +Status WindowFence(const std::string& name) {
What is usage now? If there is no usage now, we can remove it now.

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/operations.cc
> +  bool nccl_impl_available = true;
This variable seems to be useless

2020-09-18 07:55 UTC, hanbinhu commented on bluefog/common/operations.cc
> +  if (!bluefog_global.nccl_controller->IsWinObjetEmpty()) {
Typo: Objet -> Object

2020-09-18 23:41 UTC, ybc1991 commented on bluefog/common/mpi_controller.cc
> +Status MPIWinMutexAcquireImpl(std::shared_ptr<MPI_Win> mutex_win,
Done

2020-09-18 23:44 UTC, ybc1991 commented on bluefog/common/mpi_controller.cc
> +    if (is_sync) {
但是 else 那个分支要用for loop里面的rank  这样岂不是if else要分开了？

2020-09-18 23:47 UTC, ybc1991 commented on bluefog/common/nccl_win.cc
> +  id_to_name_.erase(id_to_name_.find(id));
Done

2020-09-18 23:48 UTC, ybc1991 commented on bluefog/common/nccl_win.cc
> +  return id_to_name_.at(id);
因为这个应该永远不会发生， 不过还是加一个check 来throw error 保险起见

2020-09-18 23:48 UTC, ybc1991 commented on bluefog/common/nccl_win.cc
> +  return name_to_id_.at(name);
同上

2020-09-18 23:51 UTC, ybc1991 commented on bluefog/common/nccl_win.cc
> +  return id_to_name_.at(id);
主要是这个是内部func 调用前 我先调用的 find

2020-09-18 23:51 UTC, ybc1991 commented on bluefog/torch/mpi_win_ops.cc
> +        tensor.to(::torch::Device(::torch::kCPU), /*non_blocking=*/false);
/*non_blocking=*/false， 当然是blocking更加保险

2020-09-18 23:53 UTC, ybc1991 commented on bluefog/common/operations.cc
> +Status WindowFence(const std::string& name) {
这些函数没有python 端exposed的函数 ，所以应该不会用到。 内部开发的时候我在考虑是不是nccl也不用他们， 所以先保留着。

2020-09-18 23:53 UTC, ybc1991 commented on bluefog/common/operations.cc
> +  bool nccl_impl_available = true;
用到来啊 看switch下的 default

2020-09-18 23:54 UTC, ybc1991 commented on bluefog/common/operations.cc
> +  if (!bluefog_global.nccl_controller->IsWinObjetEmpty()) {
oops, done

2020-09-19 00:52 UTC, hanbinhu commented on bluefog/common/mpi_controller.cc
> +    if (is_sync) {
我的意思是if (is_sync) { for (int rank : acquire_ranks) {do something here for self_rank} } else { for (int rank : acquire_ranks) {do something here for rank} }. 现在这个for loop中有三段if (is_sync)感觉有点蛋疼

2020-09-19 02:01 UTC, ybc1991 commented on bluefog/common/mpi_controller.cc
> +    if (is_sync) {
有道理

2020-09-19 02:28 UTC, merged