Add API to unregister window
Bluefog-Lib/bluefog pull request #72
Opened 2021-01-23 08:53 UTC by hanbinhu

2021-01-23 23:46 UTC, ybc1991 requested changes
I added a get_current_created_window_names function. I think it is better to use the global context to manage the unregister instead of the local map. Because the user may manually unregister the window

2021-01-24 01:42 UTC, hanbinhu reviewed
LGTM

2021-01-24 02:07 UTC, ybc1991 commented
I just added that function but didn't update the unregister functionality. You still need to update it and test it again

2021-01-31 03:38 UTC, ybc1991 commented on bluefog/torch/optimizers.py
> +        window_prefix: A string to identify the unique DistributedWinPutOptimizer.
A string to identify the unique DistributedWinPutOptimizer, which will be applied as the prefix for window name

2021-01-31 03:39 UTC, ybc1991 approved these changes

2021-01-31 05:43 UTC, merged